---
- name: Configure external interface
  template: src=etc/hostname.ext dest=/etc/hostname.{{ ext_int }} owner=root group=wheel mode=0640
  notify:
  - netstart

- name: Configure internal interface
  template: src=etc/hostname.int dest=/etc/hostname.{{ int_int }} owner=root group=wheel mode=0640
  notify:
  - netstart

- name: Configure hostname
  template: src=etc/myname dest=/etc/myname owner=root group=wheel mode=0644
  notify:
  - netstart

- name: Configure firewall
  copy: src=etc/pf.conf dest=/etc/pf.conf owner=root group=wheel mode=0600
  notify:
  - pf

- name: Configure dhcpd
  template: src=etc/dhcpd.conf dest=/etc/dhcpd.conf owner=root group=wheel mode0644

- name: Configure ntpd
  template: src=etc/ntpd.conf dest=/etc/ntpd.conf owner=root group=wheel mode=0644
  notify:
  - ntpd

- name: Copy common config
  copy: src={{ item }} dest=/{{ item }} owner=root group=wheel mode=0644
  with_items:
  - etc/pkg.conf
  - etc/rc.conf.local
  - etc/rc.securelevel
  - etc/sysctl.conf

- name: Configure unbound
  template: src=var/unbound/etc/unbound.conf dest=/var/unbound/etc/unbound.conf owner=root group=wheel mode=0644
  notify:
  - unbound
