---
- name: Configure external interface
  template:
    src: hostname.ext
    dest: /etc/hostname.{{ sg_common_ext_if }}
    owner: root
    group: wheel
    mode: 0640
  notify:
    - netstart

- name: Configure internal interface
  template:
    src: hostname.int
    dest: /etc/hostname.{{ sg_common_int_if }}
    owner: root
    group: wheel
    mode: 0640
  notify:
    - netstart

- name: Configure hostname
  template:
    src: myname
    dest: /etc/myname
    owner: root
    group: wheel
    mode: 0644
  notify:
    - netstart

- name: Configure firewall
  template:
    src: pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600
  notify:
    - pf

- name: Copy common config
  copy:
    src: "{{ item }}"
    dest: /etc/{{ item }}
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - pkg.conf
    - rc.securelevel
    - sysctl.conf

- name: Create rc.conf.local.d
  file:
    path: /etc/rc.conf.local.d
    state: directory
    owner: root
    group: wheel
    mode: 0644
