---
- name: Configure interfaces
  template:
    src: hostname.interface.j2
    dest: /etc/hostname.{{ item.name }}
    owner: root
    group: wheel
    mode: 0640
  notify:
    - netstart
  with_items: "{{ sg_network }}"

- name: Configure hostname
  template:
    src: myname.j2
    dest: /etc/myname
    owner: root
    group: wheel
    mode: 0644
  notify:
    - netstart

- name: Create /etc/pf.d
  file:
    path: /etc/pf.d
    state: directory
    owner: root
    group: wheel
    mode: 0750

- name: Configure base firewall rules
  template:
    src: pf.base.j2
    dest: /etc/pf.d/00-base
    owner: root
    group: wheel
    mode: 0600
  notify:
    - pf.conf

- name: Copy common config
  copy:
    src: "{{ item }}"
    dest: /etc/{{ item }}
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - pkg.conf
    - rc.securelevel
    - sysctl.conf

- name: Create rc.conf.local.d
  file:
    path: /etc/rc.conf.local.d
    state: directory
    owner: root
    group: wheel
    mode: 0644
