---
- name: Configure Interfaces
  template:
    src: hostname.interface.j2
    dest: /etc/hostname.{{ item.name }}
    owner: root
    group: wheel
    mode: 0640
  notify:
    - netstart
  with_items: "{{ sg_interfaces }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure hostname
  template:
    src: myname.j2
    dest: /etc/myname
    owner: root
    group: wheel
    mode: 0644
  notify:
    - netstart

- name: Create /etc/pf.d
  file:
    path: /etc/pf.d
    state: directory
    owner: root
    group: wheel
    mode: 0750

- name: Configure base firewall rules
  template:
    src: 00-pf-base.j2
    dest: /etc/pf.d/00-base
    owner: root
    group: wheel
    mode: 0600
  notify:
    - pf.conf

- name: Configure base firewall blocks
  copy:
    src: 90-pf-baseblocks
    dest: /etc/pf.d/90-baseblocks
    owner: root
    group: wheel
    mode: 0600
  notify:
    - pf.conf

- name: Copy common config
  copy:
    src: "{{ item }}"
    dest: /etc/{{ item }}
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - rc.securelevel
    - sysctl.conf

- name: Configure SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sshd

- name: Copy SSH banner
  copy:
    src: "{{ sshd_banner | default('sshd_banner') }}"
    dest: /etc/ssh/sshd_banner
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sshd
    
- name: Configure package system
  template:
    src: pkg.conf.j2
    dest: /etc/pkg.conf
    owner: root
    group: wheel
    mode: 0644
    
- name: Template Startup Control Files
  template:
    src: "{{ item }}.j2"
    dest: /etc/{{ item }}
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - hosts
    - myname
    - mygate
    - resolv.conf.boot
    - resolv.conf.final

- name: Create rc.conf.local.d
  file:
    path: /etc/rc.conf.local.d
    state: directory
    owner: root
    group: wheel
    mode: 0644

- name: Create rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: wheel
    mode: 0644
  when: sg_networks|selectattr('services', 'issuperset', ['dhcp'])|list

