---
- name: rc.conf.local
  assemble: src=/etc/rc.conf.local.d dest=/etc/rc.conf.local owner=root group=wheel mode=0644

- name: netstart
  command: sh /etc/netstart

- name: dhcpd
  command: /etc/rc.d/dhcpd restart

- name: ntpd
  command: /etc/rc.d/ntpd restart

- name: nsd
  command: /etc/rc.d/nsd reload

- name: unbound
  command: /etc/rc.d/unbound reload

- name: pf
  command: pfctl -f /etc/pf.conf
